import { useState } from 'react';
import { Position } from 'reactflow';
import { BaseNode } from './BaseNode';
import { useStore } from '../store';

/**
 * ApiNode Component
 * 
 * This component represents an HTTP/API node in our visual workflow builder.
 * It allows developers and AI flow builders to make external HTTP requests (GET, POST, PUT)
 * as part of a Directed Acyclic Graph (DAG) pipeline.
 * 
 * Connection Ports:
 * - Left Handle (Target): Receives trigger events or data payloads from upstream.
 * - Right Handle (Source): Outputs the server response (e.g., JSON response, status code).
 *
 * @param {object} props
 * @param {string} props.id - The unique identifier generated by React Flow.
 * @param {object} props.data - Node state payload (URL, method, execution status, execution result).
 * @param {boolean} props.selected - Visual selection state inside the react-flow canvas.
 */
export const ApiNode = ({ id, data, selected }) => {
  // Local state to keep track of user input URL
  const [url, setUrl] = useState(data?.url || '');
  
  // Local state to manage selected HTTP request method
  const [method, setMethod] = useState(data?.method || 'GET');
  
  // Hook from global Zustand store to dynamically sync local edits into global flow state
  const updateNodeField = useStore((state) => state.updateNodeField);

  // Connection ports: Right (Source) to pass responses and Left (Target) to accept trigger payload
  const handles = [
    { id: `${id}-trigger`, type: 'target', position: Position.Left },
    { id: `${id}-response`, type: 'source', position: Position.Right }
  ];

  return (
    <BaseNode 
      id={id} 
      label="API Request" 
      icon="🌐" 
      color="#0ea5e9" 
      selected={selected} 
      handles={handles} 
      status={data?.status} 
      result={data?.result}
    >
      {/* Dropdown menu to configure HTTP Methods */}
      <div className="node-field">
        <label>Method</label>
        <select 
          value={method} 
          onChange={(e) => {
            setMethod(e.target.value);
            updateNodeField(id, 'method', e.target.value);
          }}
        >
          <option value="GET">GET</option>
          <option value="POST">POST</option>
          <option value="PUT">PUT</option>
        </select>
      </div>
      
      {/* Input box to specify target URL endpoint */}
      <div className="node-field">
        <label>URL</label>
        <input 
          type="text" 
          value={url} 
          onChange={(e) => {
            setUrl(e.target.value);
            updateNodeField(id, 'url', e.target.value);
          }} 
          placeholder="https://api.example.com"
        />
      </div>
    </BaseNode>
  );
};

